version: "3"

services:
  adminer:
    container_name: sidoka_adminer
    image: adminer
    expose:
      - "8080"
    volumes:
      - ./data/adminer.css:/var/www/html/adminer.css
      - ./data/plugins-enabled:/var/www/html/plugins-enabled/
      - ./data/index.php:/var/www/html/index.php
  nginx:
    container_name: sidoka_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/etc/nginx/error_log.log warn
    ports:
      - 80:80