version: "3"

services:
  adminer:
    container_name: sidoka_adminer
    image: adminer
    restart: always
    ports:
      - 7777:8080
    volumes:
      - ./data/adminer.css:/var/www/html/adminer.css
      - ./data/plugins-enabled:/var/www/html/plugins-enabled/
      - ./data/index.php:/var/www/html/index.php